global:
  scale: 100
  cpuRatio: 40
  memRatio: 100 
  replicas: 1
  minReplicas: 1
  maxSurge: 1
  maxUnavailable: 25%
  containerRegistry: /
  httpConnectTimeout: 60
  httpSendTimeout: 600
  httpReadTimeout: 600
  customerId: DEV_CUST 
  customerName: DEV_CUST must change for PROD
  installationId: DEV_INST
  nodeSelector: {}
  tolerations: []
  affinity: {}
  deploymentModel: REMOTE
  techDocUrl: https://docs.ifs.com/techdocs/25r1/
  cloudDocUrl: /ifsdoc/documentation/en/