//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.544
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ifs.Application.Trnord.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Ifs.Application.Trnord.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;0 - Customer Invoice.
        /// </summary>
        public static string TEXT_CustomerInvoiceDetails {
            get {
                return ResourceManager.GetString("TEXT_CustomerInvoiceDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;0 - Customer Invoice - &amp;1.
        /// </summary>
        public static string TEXT_CustomerInvoiceDetailsExt {
            get {
                return ResourceManager.GetString("TEXT_CustomerInvoiceDetailsExt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;0 - Orverview - Customer Invoices.
        /// </summary>
        public static string TEXT_CustomerInvoiceOverview {
            get {
                return ResourceManager.GetString("TEXT_CustomerInvoiceOverview", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;0 - Customer Order.
        /// </summary>
        public static string TEXT_CustomerOrderDetails {
            get {
                return ResourceManager.GetString("TEXT_CustomerOrderDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;0 - Customer Order - &amp;1.
        /// </summary>
        public static string TEXT_CustomerOrderDetailsExt {
            get {
                return ResourceManager.GetString("TEXT_CustomerOrderDetailsExt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;0 - Orverview - Customer Orders.
        /// </summary>
        public static string TEXT_CustomerOrderOverview {
            get {
                return ResourceManager.GetString("TEXT_CustomerOrderOverview", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Preferred inventory not available..
        /// </summary>
        public static string TEXT_ERROR_InventoryNotAvaialbe {
            get {
                return ResourceManager.GetString("TEXT_ERROR_InventoryNotAvaialbe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;0 - External Customer.
        /// </summary>
        public static string TEXT_ExternalCustomerDetails {
            get {
                return ResourceManager.GetString("TEXT_ExternalCustomerDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;0 - Orverview - External Customers.
        /// </summary>
        public static string TEXT_ExternalCustomerOverview {
            get {
                return ResourceManager.GetString("TEXT_ExternalCustomerOverview", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;0 - Internal Customers.
        /// </summary>
        public static string TEXT_InternalCustomerOverview {
            get {
                return ResourceManager.GetString("TEXT_InternalCustomerOverview", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;0 - Reservation Details for Order - &amp;1.
        /// </summary>
        public static string TEXT_OrderReservationDetails {
            get {
                return ResourceManager.GetString("TEXT_OrderReservationDetails", resourceCulture);
            }
        }
    }
}
